clicknbees/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from directory.api import EmpresaResource
from tastypie.api import Api

api = Api(api_name = "v1")
api.register(EmpresaResource())


# MEDIA upload imports
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Directory URLS
       #(r'^$', TemplateView.as_view(template_name = "coral/index.html")),
    url(r'', include('directory.urls')),
    url(r'^perfil/', include('perfil.urls')),
    url(r'^dependencias/', include('dependencias.urls')),
    url(r'^about/', include('landing.urls')),
    #url(r'^beta/', include('landing.urls')),

    # API urls
    url(r'^api/', include(api.urls)),

    # New configuration
    url(r'^listado-empresas/$', TemplateView.as_view(template_name = "remake/lista.html"), name = "index"),
    #url(r'^dependencias/$', TemplateView.as_view(template_name = "remake/dependencias.html")),
    url(r'^featured/$', TemplateView.as_view(template_name = "remake/featured.html")),
    url(r'^registro-empresa/$', TemplateView.as_view(template_name = "remake/registro-empresa.html")),

    url(r'^beta/android-app/$', TemplateView.as_view(template_name = "remake/android.html")),

    url(r'^landing/', include('landing.urls')),




) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

perfil/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from .views import EditarUsuario, CrearEmpresa, EditarEmpresa

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', TemplateView.as_view(template_name = 'perfil/index.html'), name = "perfil"),
    url(r'^(?P<pk>\d+)/editar/$', EditarUsuario.as_view(template_name = 'perfil/editar.html'), name="editar_perfil"),
    url(r'^crear/$', CrearEmpresa.as_view(), name = "crear_empresa"),
    url(r'^empresa/(?P<pk>\d+)/editar/$', EditarEmpresa.as_view(), name = "editar_empresa"),

)

directory/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from geoposition.fields import GeopositionField
from cloudinary.models import CloudinaryField
from autoslug import AutoSlugField
from randomslugfield import RandomSlugField

class Empresa(models.Model):
    user = models.ForeignKey(User, unique = True)
    nombre = models.CharField(max_length = 80, unique = True)
    slug = AutoSlugField(populate_from = "nombre", always_update = True, unique_with = "id")
    random_slug = RandomSlugField(length = 20)
    logotipo = models.URLField(null = True, blank = True)
    horarios = models.TextField(null = True, blank = True)
    giro = models.CharField(max_length = 40)
    categoria = models.CharField(max_length = 35, null = True, blank = True)
    descripcion = models.TextField(max_length = 400, null = True, blank = True)
    email = models.EmailField()
    telefono = models.CharField(max_length = 20, null = True, blank = True)
    celular = models.CharField(max_length = 15, null = True, blank = True)
    direccion = models.CharField(max_length = 100)
    colonia = models.CharField(max_length = 50)
    cp = models.IntegerField()

    # Social Accounts
    facebook = models.URLField(null = True, blank = True)
    twitter = models.URLField(null = True, blank = True)
    youtube = models.URLField(null = True, blank = True)

    def __unicode__(self):
        return self.nombre

perfil/models.py
from django.db import models

# Create your models here.

perfil/views.py
from django.shortcuts import render
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.auth.models import User
from directory.models import Empresa
from directory.forms import EmpresaForm
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

class EditarUsuario(UpdateView):
    model = User
    fields = ["username", "first_name", "last_name", "email"]
    template_name = "perfil/editar.html"
    #success_url = "/perfil/"

    def get_success_url(self):
        return reverse('perfil', kwargs = {"pk": self.request.user.id})

class CrearEmpresa(CreateView):
    model = Empresa
    form_class = EmpresaForm
    template_name = "perfil/crear_empresa.html"
    success_url = "/perfil/"

    def get_success_url(self):
        return reverse('perfil', kwargs = {"pk": self.request.user.id})

    def form_valid(self, form):
        empresa = form.save(commit = False)
        empresa.user = User.objects.get(id = self.request.user.id)
        empresa.save()
        return HttpResponseRedirect(self.get_success_url())

class EditarEmpresa(UpdateView):
    model = Empresa
    form_class = EmpresaForm
    template_name = "perfil/editar_empresa.html"
    #$success_url = "/perfil/"

    def get_queryset(self):
        queryset = Empresa.objects.filter(pk = self.request.user.id)
        return queryset

    def get_success_url(self):
        return reverse('perfil', kwargs = {"pk": self.request.user.id})

templates/perfil/crear_empresa.html
{% extends "remake/base.html" %}

{% load staticfiles %}
{% load url from future %}
{% load widget_tweaks %}

{% block content %}
	<div class="layout-app" style="margin-top: 1ex;">
		<div class="container">			
			<h2 style="text-align: center;">Registro de Empresa</h2>
			<div class="col-md-1"></div>
			<div class="col-md-10">			
				<br>
				<br>
				<hr>
				<form action="" method="post">
				{% csrf_token %}		
				{{form.errors}}								
					<div class="row">
						<div class="col-md-5">
							<h4>Nombre de tu empresa</h4> 
							{% render_field form.nombre %} <br><br>
							<h4>Logotipo</h4> 
							{% render_field form.logotipo %} <br><br>							
							<h4>Descripción</h4> 
							{% render_field form.descripcion %}	<br><br>
							<h4>Email</h4> 
							{% render_field form.email %} <br><br>
							<h4>Horarios</h4>
							{% render_field form.horarios %}
						</div>
						<div class="col-md-2"></div>
						<div class="col-md-5">
							<h4>Telefono</h4> 
							{% render_field form.telefono %} <br><br>
							<h4>Celular</h4> 						
							{{form.celular}} <br><br>						
							<h4>Dirección</h4> 
							{% render_field form.direccion %} <br><br>
							<div class="row">
								<div class="col-md-8">									
									<h4>Colonia </h4>{% render_field form.colonia %}
								</div>
								<div class="col-md-4">									
									<h4>C.P.</h4> {% render_field form.cp %}
								</div>
							</div>
							<br>
							<h4>Facebook</h4> 
							{% render_field form.facebook %} <br><br>
							<h4>Twitter</h4> 
							{% render_field form.twitter %} <br><br>
							<br>
							<button type="submit" class="btn btn-primary">Registrar Empresa</button>	
						</div> 
					</div>					
				</form>				
			</div>
		</div>
	</div>

{% endblock %}

templates/perfil/editar.html
{% extends "remake/base.html" %}

{% load staticfiles %}
{% load url from future %}
{% load widget_tweaks %}

{% block content %}
	<div class="container">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<h2>Edita tu perfil</h2>
			<form action="" method="post">{% csrf_token %}
			    {{ form.as_p }}
			    <input type="submit" value="Editar" />
			</form>
		</div>
	</div>
{% endblock %}

templates/perfil/editar_empresa.html
{% extends "remake/base.html" %}

{% load staticfiles %}
{% load url from future %}
{% load widget_tweaks %}

{% block content %}
	<div class="layout-app" style="margin-top: 20px;">
		<div class="row row-app">
			<h2 style="text-align: center;">Modifica la información de tu empresa</h2>
			<div class="col-md-1"></div>
			<div class="col-md-10">			
				<br>
				<br>
				<hr>
				<form action="" method="post">
				{% csrf_token %}		
				{{form.errors}}								
					<div class="row">
						<div class="col-md-5">
							<h4>Nombre de tu empresa</h4> 
							{% render_field form.nombre %} <br><br>
							<h4>Logotipo</h4> 
							{% render_field form.logotipo %} <br><br>							
							<h4>Descripción</h4> 
							{% render_field form.descripcion %}	<br><br>
							<h4>Email</h4> 
							{% render_field form.email %}
						</div>
						<div class="col-md-2"></div>
						<div class="col-md-5">
							<h4>Telefono</h4> 
							{% render_field form.telefono %} <br><br>
							<h4>Celular</h4> 						
							{{form.celular}} <br><br>						
							<h4>Dirección</h4> 
							{% render_field form.direccion %} <br><br>
							<div class="row">
								<div class="col-md-8">									
									<h4>Colonia </h4>{% render_field form.colonia %}
								</div>
								<div class="col-md-4">									
									<h4>C.P.</h4> {% render_field form.cp %}
								</div>
							</div>
							<br>
							<h4>Facebook</h4> 
							{% render_field form.facebook %} <br><br>
							<h4>Twitter</h4> 
							{% render_field form.twitter %} <br><br>
							<br>
							<button type="submit" class="btn btn-primary">Registrar Empresa</button>	
						</div> 
					</div>					
				</form>				
			</div>
		</div>
	</div>

{% endblock %}

templates/perfil/index.html
{% extends "remake/base.html" %}

{% block content %}
	<div class="layout-app">
		<div class="row row-app" style="margin-top: -ex;">
			<div class="col-separator col-unscrollable box col-separator-first">
				<div class="col-md-3"></div>
				<div class="col-md-6">
					{% if user.is_authenticated %}
						<h2>Hola {{user.username}}</h2>
						<h3>Información de Usuario: </h3>
						<p>Nombre: {{user.first_name}}</p>
					{% if user.last_name %}
						<p>Apellido: {{user.last_name}}</p>
					{% endif %}
						<p>Email: {{user.email}}</p>
					{% else %}
						No has ingresado a tu cuenta. <br>
						<a href="/accounts/login">Login</a><br>
						No tienes cuenta?: 
						<a href="/accounts/login">Registrate</a>	
					{% endif %}	
					<br>
					<hr>
					{% if user.is_authenticated %}
						Editar tu cuenta: <a href="{% url 'editar_perfil' pk=user.id %}">Editar</a>
					{% endif %}
					<br>
					<hr>	
					{% if user.is_authenticated %}
						{% if user.empresa_set.first %}
							Editar empresa: <a href="{% url 'editar_empresa' pk=user.id %}">Edita tu Empresa</a>
						{% else %}
							Crear empresa: <a href="{% url 'crear_empresa' %}">Aquí</a>	<br>
						{% endif %}
					{% endif %}
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/perfil/promociones.html
<ul>
	{% for promocion in promociones %}
	<li>{{promocion.nombre}}</li>
	{% enfor %}
</ul>